spring:
  profiles:
    #引入数据库配置文件
    include: db,sys
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true #显示sql
logging:
  config: classpath:log4j2.xml

#actuator
management:
  server:
    port: 8004
    servlet:
      context-path: /actuator
  #开启全部结点
  endpoints:
    web:
      exposure:
        include: "*"

